SimpleHomestay/Frontpage/urls.py
from django.urls import path
from . import views


app_name = 'Frontpage'


urlpatterns = [
    path('' , views.home , name='home'),
]

SimpleHomestay/Room/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView



app_name = 'Room'


urlpatterns = [
    path('',views.Roompage , name='Roompage'),
    path('booking/<int:id>', views.Booking.as_view(), name='Booking',),
    path('booking/<int:id>/<int:year>/<int:month>/', views.Booking.as_view(), name='Booking',),
]

SimpleHomestay/SimpleHomestay/urls.py
from django.contrib import admin

from django.urls import path , include, reverse

from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Frontpage.urls' , namespace='Frontpage')),
    path('room/', include('Room.urls' , namespace='Room')),
]


urlpatterns +=  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns +=  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SimpleHomestay/Room/models.py
from django.db import models
import datetime
from django.utils import timezone

# Create your models here.

class Room(models.Model):
    name = models.CharField(max_length=50)
    bed_type = models.CharField(max_length=50, default='SOME STRING')
    beds_number = models.PositiveIntegerField()
    capacity = models.IntegerField(default = 0)
    image = models.ImageField(upload_to='room/' , null=True)
    price = models.PositiveIntegerField()
    promotion = models.TextField()
    facility = models.TextField()

    def __str__(self):
        return self.name


    class Meta:
        verbose_name = 'Room'
        verbose_name_plural = 'Room'

class Reservation(models.Model):
    room = models.ForeignKey(Room,on_delete=models.CASCADE,null=True)
    name = models.CharField(max_length=50)

    email = models.EmailField()
    phone_number = models.CharField(max_length=12)

    NumberOfGuest = models.PositiveIntegerField(default = 0)

    CheckIn = models.DateTimeField()
    CheckOut = models.DateTimeField()

    nights = models.PositiveIntegerField(default = 0)

    TotalCost = models.PositiveIntegerField(default = 0,null=True)
    notes  = models.TextField()


    class Meta:
        verbose_name_plural = 'Reservation'

    def __str__(self):
         return self.name



class Schedule(models.Model):
    """Schedule"""
    Room_no = (
        ("!","!"),
        ("@","@"),
        ("#","#"),
        ("$","$"),
    )
    summary = models.CharField( max_length=1, choices=Room_no)
    description = models.TextField('description', blank=True)
    start_time = models.TimeField('start_time', default=datetime.time(7, 0, 0))
    end_time = models.TimeField('end_time', default=datetime.time(7, 0, 0))
    date = models.DateField('date')
    

    def __str__(self):
        return self.summary

SimpleHomestay/Room/forms.py
from django import forms
from django.forms import ModelForm, DateInput
from bootstrap_datepicker_plus import DatePickerInput
from .models import Reservation,Schedule


class ReserveForm(forms.ModelForm):
    class Meta :
        model = Reservation

        fields = ('name','email', 'phone_number','NumberOfGuest','CheckIn','CheckOut','notes')
        widgets = {
            'CheckIn': DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
            'CheckOut': DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
        }

    def __init__(self, *args, **kwargs):
        super(ReserveForm, self).__init__(*args, **kwargs)
        # input_formats parses HTML5 datetime-local input to datetime field
        self.fields['start_time'].input_formats = ('%Y-%m-%dT%H:%M',)
        self.fields['end_time'].input_formats = ('%Y-%m-%dT%H:%M',)

class BS4ScheduleForm(forms.ModelForm):
    """Bootstrapに対応するためのModelForm"""

    class Meta:
        model = Schedule
        fields = ('summary', 'description', 'start_time', 'end_time')
        widgets = {
            'summary': forms.TextInput(attrs={
                'class': 'form-control',
            }),
            'description': forms.Textarea(attrs={
                'class': 'form-control',
            }),
            'start_time': forms.TextInput(attrs={
                'class': 'form-control',
            }),
            'end_time': forms.TextInput(attrs={
                'class': 'form-control',
            }),
        }

    def clean_end_time(self):
        start_time = self.cleaned_data['start_time']
        end_time = self.cleaned_data['end_time']
        if end_time <= start_time:
            raise forms.ValidationError(
                'The end time must be later than the start time'
            )
        return end_time


class SimpleScheduleForm(forms.ModelForm):
    """シンプルなスケジュール登録用フォーム"""

    class Meta:
        model = Schedule
        fields = ('summary', 'date',)
        widgets = {
            'summary': forms.TextInput(attrs={
                'class': 'form-control',
            }),
            'date': forms.HiddenInput,
        }

SimpleHomestay/Room/views.py
from __future__ import unicode_literals
from django.shortcuts import render, redirect
import datetime
from .models import Room,Reservation
from .forms import ReserveForm

from bootstrap_datepicker_plus import DatePickerInput


from datetime import datetime, timedelta, date
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.views import generic
from django.urls import reverse
from django.utils.safestring import mark_safe

import calendar


from .forms import ReserveForm

# Create your views here.

def Roompage(request):
    Roompage = Room.objects.all()
    template = 'Room/rooms.html'
    context = {
        'Roompage' : Roompage ,
    }
    return render(request , template , context)


#    def BookingTotalCalculation(CheckIn,CheckOut,TotalCost,nights):
#        price = Room.price
#        CheckOut = datetime.strptime(str(CheckOut), "%m/%d/%Y")
#        CheckIn = datetime.strptime(str(CheckIn), "%m/%d/%Y")
#        timedeltaSum = CheckOut - CheckIn
#        nights = timedeltaSum.days
#        TotalCost = nights * price
#        context = {
#            'nights': nights,
#            'TotalCost' : TotalCost ,
#        }
#        return render(context)

##### Here's code for the view to look up the event objects for to put in
# the context for the template. It goes in your app's views.py file (or
# wherever you put your views).
#####
import datetime
from django.shortcuts import redirect, render
from django.views import generic
from .forms import BS4ScheduleForm, SimpleScheduleForm
from .models import Schedule
from . import mixins


class MonthCalendar(mixins.MonthCalendarMixin, generic.TemplateView):
    """月間カレンダーを表示するビュー"""
    template_name = 'Room/month.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        calendar_context = self.get_month_calendar()
        context.update(calendar_context)
        return context


class WeekCalendar(mixins.WeekCalendarMixin, generic.TemplateView):
    """週間カレンダーを表示するビュー"""
    template_name = 'Room/week.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        calendar_context = self.get_week_calendar()
        context.update(calendar_context)
        return context


class WeekWithScheduleCalendar(mixins.WeekWithScheduleMixin, generic.TemplateView):
    """スケジュール付きの週間カレンダーを表示するビュー"""
    template_name = 'Room/week_with_schedule.html'
    model = Schedule
    date_field = 'date'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        calendar_context = self.get_week_calendar()
        context.update(calendar_context)
        return context


class MonthWithScheduleCalendar(mixins.MonthWithScheduleMixin, generic.TemplateView,):
    """スケジュール付きの月間カレンダーを表示するビュー"""
    template_name = 'Room/month_with_schedule.html'
    model = Schedule
    date_field = 'date'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        calendar_context = self.get_month_calendar()
        context.update(calendar_context)
        return context


class MyCalendar(mixins.MonthCalendarMixin, mixins.WeekWithScheduleMixin, generic.CreateView):
    """月間カレンダー、週間カレンダー、スケジュール登録画面のある欲張りビュー"""
    template_name = 'Room/mycalendar.html'
    model = Schedule
    date_field = 'date'
    form_class = BS4ScheduleForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        week_calendar_context = self.get_week_calendar()
        month_calendar_context = self.get_month_calendar()
        context.update(week_calendar_context)
        context.update(month_calendar_context)
        return context

    def form_valid(self, form):
        month = self.kwargs.get('month')
        year = self.kwargs.get('year')
        day = self.kwargs.get('day')
        if month and year and day:
            date = datetime.date(year=int(year), month=int(month), day=int(day))
        else:
            date = datetime.date.today()
        schedule = form.save(commit=False)
        schedule.date = date
        schedule.save()
        return redirect('Room:mycalendar', year=date.year, month=date.month, day=date.day)


class MonthWithFormsCalendar(mixins.MonthWithFormsMixin, generic.CreateView):
    """フォーム付きの月間カレンダーを表示するビュー"""
    template_name = 'Room/month_with_forms.html'
    model = Schedule
    model = Room
    date_field = 'date'
    form_class = SimpleScheduleForm

    def get(self, id, request, **kwargs):
        context = self.get_month_calendar()
        context['Room'] = Room.objects.get(id=id)
        return render(request, self.template_name, context)

    def post(self, request, **kwargs):
        context = self.get_month_calendar()
        formset = context['month_formset']
        if formset.is_valid():
            formset.save()
            return redirect('Room:month_with_forms')

        return render(request, self.template_name, context)


def calendar(request):
  context = locals()
  template = 'Room/calendar.html'
  return render(request,template,context)

#def event(request, event_id=None):
#    instance = Event()
#    if event_id:
#        instance = get_object_or_404(Event, pk=event_id)
#    else:
#        instance = Event()

#    form = EventForm(request.POST or None, instance=instance)
#    if request.POST and form.is_valid():
#        form.save()
#        return HttpResponseRedirect(reverse('cal:calendar'))
#    return render(request, 'cal/event.html', {'form': form})

#def Booking(request,id):
#    room  = Room.objects.get(id=id)
#    template_name =  'Room/booking.html'
#
#    if request.method == 'POST':
#        reserve_form = ReserveForm(request.POST)
#
#        if reserve_form.is_valid():
#            reserve = reserve_form.save(commit=False)
#            reserve.reserve_form = room
#            reserve.save()
#            return HttpResponseRedirect('/room/')
#
#        else:
#            reserve_form = ReserveForm()
#
#            return render(request , template , context)

class Booking(mixins.MonthWithScheduleMixin, generic.TemplateView):
    """スケジュール付きの月間カレンダーを表示するビュー"""
    template_name = 'Room/booking.html'
    model = Schedule
    date_field = 'date'

    def get_context_data(self, id, **kwargs):
        context = super().get_context_data(**kwargs)
        calendar_context = self.get_month_calendar()
        context.update(calendar_context)
        context['Room'] = Room.objects.get(id=id)
        return context

SimpleHomestay/Room/templates/Room/booking.html
{% load i18n %}
{% load static %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}


<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

	<title>Bookings</title>

	<!-- Google font -->
	<link href="https://fonts.googleapis.com/css?family=Playfair+Display|Quicksand" rel="stylesheet">

	<!-- Bootstrap -->
	<link type="text/css" rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />

	<!-- Custom stlylesheet -->
	<link type="text/css" rel="stylesheet" href="{% static 'css/style.css' %}" />
	<link rel="stylesheet" href="{% static 'jquery-ui/themes/base/all.css' %}" type="text/css" media="screen">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.2/css/all.css" integrity="sha384-/rXc/GQVaYpyDdyxK+ecHPVYJSN9bmVFBvjA/9eOB+pb3F2w2N6fc5qB9Ew5yIns" crossorigin="anonymous">
	<link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">

</head>

<body>


	<div class="container text-center">
		<h1 style="font-size: 65px; font-weight: 400;">The Home Stay</h1>
		<h3 style="letter-spacing: 10px; font-size: 18px;">RESERVATION</h3>
	</div>	<!-- end container -->


	<div class="container">

		<hr>

		<nav aria-label="breadcrumb bg-none">
			<ol class="breadcrumb" style="letter-spacing: 0.3rem; font-size: 22px; font-weight: 300;">
				<li class="breadcrumb-item"><a class="blackfont" href="{% url 'Frontpage:home' %}">Home</a></li>
				<li class="breadcrumb-item"><a class="blackfont" href="{% url 'Room:Roompage' %}">Rooms</a></li>
				<li class="breadcrumb-item active" aria-current="page">Reservation</li>
			</ol>
		</nav>

		<hr>

	</div><!-- end containers -->



	<div class="hero-header">
		<div class="hero-text">
				<h1>Experience the wilderness at the top of the hill.</h1>
				<p class="lead">Check out our accommodation options and book today.</p>
		</div>
	</div>



	<div class="container-fluid pt-3">

		<div class="card shadow bg-success">
			<div class="card-body">

				<div class="row">

					<div data-aos="fade-right" class="col-md-6 p-1 my-auto">
						<h2>Room Details</h2>

						<p>Type : {{Room.name}}</p>
						<p>Capacity : {{Room.capacity}} person</p>
						<p>Beds : {{Room.beds_number}} </p>
						<p>Price : RM{{Room.price}}</p>
						<p>Facility : {{Room.facility}}</p>
					</div><!-- end col-6 -->

					<div data-aos="fade-left" class="col-md-6 p-1 my-auto">
						<h4>How to book?</h4>
						<p><strong>STEP 1:</strong> From the calendar below, select <b>only the night(s)</b> of your stay.</p>
						<p style="color: #888"> Examples:<br> <b>If for 1 night</b> - check-in 1/1/2019 and check-out 2/1/2019, select <b>only 1/1/2019.</b><br> <b>If for 2 nights</b> - check-in 1/1/2019 and check-out 3/1/2019, select <b>only 1/1/2019 and 2/1/2019.</b><br></p>
						<p><strong>STEP 2:</strong> Fill up all the details in the booking form below. <br><strong>STEP 3:</strong> Check the <b>TOTAL COST</b> and press <b>SEND</b>.</p>
						<p>We will confirm your booking via email together with the payment information.</p>
					</div><!-- end col-6 -->
					<div class="col text-center">
						<p>
							<a href="" target="_blank" class="redfont">MUST-READ FAQs: Please <span style="text-decoration:underline">read this</span> carefully. It's not the usual yada yada!</a>
						</p>
					</div>
				</div><!-- end row -->
			</div><!-- end card-body -->
		</div><!-- end card -->
	</div><!-- end container -->

	<hr class="style3">

	<div class="container">
	<div class="card shadow bg-success">
		<div class="card-body">

			<div class="row">

				<div data-aos="fade-right" class="col-md-6 p-2 my-auto">
					<h4>Rates</h4>
					<table>
						<tbody>
							<tr>
								<th>Day</th>
								<th>Per Night</th>
							</tr>
							<tr>
								<td>Monday-Thursday</td>
								<td>RM{{Room.price}}</td>
							</tr>
							<tr>
								<td>Friday &amp; Sunday</td>
								<td>RM{{Room.price}}</td>
							</tr>
							<tr>
								<td>Saturday</td>
								<td>RM{{Room.price}}</td>
							</tr>
							<tr>
								<td>Extra bed (max 4 pax)</td>
								<td>RM50 each</td>
							</tr>
							<tr>
								<td>Kitchen</td>
								<td>Yes</td>
							</tr>
							<tr>
								<td>BBQ area</td>
								<td>Yes</td>
							</tr>
						</tbody>
					</table>
					<p>Please email us at test@mail.com if you require any further assistance. Or, call us at 012-3246552 from 8am-7pm (Mon-Sat only).</p>
				</div><!-- end col-4 -->

				<div data-aos="fade-left" class="col-md-6 p-2 my-auto">
					<h4>Important Info</h4>
					<table>
						<tbody>
							<tr>
								<th>ITEM</th>
								<th>DESCRIPTION</th>
							</tr>
							<tr>
								<td>NO RECEPTION</td>
								<td>There is no reception area. We practice a lay back style for check-in procedure. When you arrive, just mention your name used for booking and make your balance payment (if any) to the caretaker. Then, they will guide you to your
									shed/house.</td>
							</tr>
							<tr>
								<td>EATERY OUTLET/STALLS</td>
								<td>There is no food or drink sold at the site. Please bring your own food &amp; drink.</td>
							</tr>
							<tr>
								<td>BASIC AMENITIES</td>
								<td>Items that are NOT provided: Towels, toiletries, hair dryers, mosquito repellent, TV, WIFI.</td>
							</tr>
						</tbody>
					</table>
				</div><!-- end col-4 -->
			</div><!-- end row -->
		</div><!-- end card-body -->
	</div><!-- end card -->
	</div><!-- end container -->


	<hr class="style3">
																										<!--Booking Calendar -->
<div class="container-fluid">


	<div class="card shadow bg-success">

		<h1 data-aos="fade-up" class="pt-3" align="center">Reservation Calendar</h1>

		<div class="card-body">

			<div id="content-main">

				<style>
					table {
						table-layout: fixed;
					}

					td>div {
						height: 100px;
						overflow: auto;
						white-space: normal;
					}
				</style>

				<div class="btn-group" style="width: 100%;">
					<a href="{% url 'Room:Booking' Room.id month_previous.year month_previous.month %}#calendar" style="width:100%" name="calendar" class="btn btn-outline-dark float-left"> Previous Month </a>
					<a href="" class="btn btn-outline-dark float-center" style="width:100%" target=""> <strong>{{ month_current | date:" Y / m  " }}</strong></a>
					<a href="{% url 'Room:Booking' Room.id month_next.year month_next.month %}#calendar" class="btn btn-outline-dark float-right" style="width:100%" name="calendar"> Next Month </a>
				</div>

				<table class="table table-striped table-warning">
					<thead>
						<tr>
							{% for w in week_names %}
							<th style="text-align:justify">{{ w }}</th>
							{% endfor %}
						</tr>
					</thead>
					<tbody>
						{% for week_day_schedles in month_day_schedules %}
						<tr>
							{% for day, schedules in week_day_schedles.items %}
							{% if now == day %}
							<td class="table-success">
								{% else %}
							<td>
								{% endif %}

								<div style="padding:2px;">
									{% if month_current.month != day.month %}
									{{ day | date:"m/d" }}
									{% else %}
									{{ day.day }}
									{% endif %}
									<br>
									<br>
									{% for schedule in schedules %}
									<span style="padding:1px ;">{{schedule.summary}}</span>
									{% endfor %}
								</div>
							</td>
							{% endfor %}
						</tr>
						{% endfor %}
					</tbody>
				</table><!-- end table -->

			</div><!-- end content-main -->

			<hr class="style3">

			<div class="pt-1 text-center">

				<h5 data-aos="fade-up">Pick your date & book now.</h5>
				<a data-aos="fade-up" href="{% url 'Room:Booking' Room.id %}" class="btn button black" target="_blank">Reserve</a>

			</div>

		</div><!-- end card-body -->

	</div><!-- end card -->


</div><!-- end container fluid -->

																				<!-- end of Booking Calendar -->


<div class="container pt-5">
	<div class="card shadow bg-success">
		<div data-aos="fade-up" class="card-body">

			<h4>Terms and Conditions</h4>
			<ul class="disc">
				<li>Check-in after 2pm, check-out before 12 noon.</li>
				<li>All rates quoted are nett.</li>
				<li>Rates are per night stay and is applicable for up to 10 adults per warehouse.</li>
				<li>Maximum each warehouse can accomodate is 14 pax. 11th to 14th guests additional RM50 each.</li>
				<li>Children ages 8 years and above to be charged as adult.</li>
				<li><strong>Not allowed to have day trippers (no stay over night guests) come along for the trip.</strong></li>
				<li>No meals included.</li>
				<li>Public holidays surcharge of RM100 per shed. For eves of Christmas and New Year, surcharge of 50% per shed.</li>
				<li>The booking is for accommodation only. Any request for event, pre-wedding photo shoot or filming - please email us at serendah@sekeping.com by stating the usage/purpose of your booking.</li>
				<li>For viewing purposes, please make prior appointment - Mon-Thu / 12noon-2pm.</li>
			</ul>

		</div>
	</div>
</div>

<!-- ======================================= end page content ============================================= -->


<footer class="text-center pt-3">
	<ul class="nav justify-content-center">
		<li class="nav-item p-2 mb-1 rounded">
			<a class="nav-link" href="#"><i class="fab fa-black fa-facebook fa-3x"></i></a>
		</li>
		<li class="nav-item p-2 mb-1 rounded">
			<a class="nav-link" href="#"><i class="fab fa-black fa-instagram fa-3x"></i></a>
		</li>
		<li class="nav-item p-2 mb-1 rounded">
			<a class="nav-link" href="#"><i class="fab fa-black fa-twitter fa-3x"></i></a>
		</li>
	</ul>
	<p class="my-1 footerFont">Copyright 2019</p>
	<h6 class="footerFont">Created by MADTechnologies</h6>
</footer>


<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

<link rel="stylesheet" href="{% static 'bootstrap/dist/css/bootstrap.css' %}" type="text/css" media="screen">
<script type="text/javascript" src="{% static 'jquery/dist/jquery.js' %}"></script>
<script type="text/javascript" src="{% static 'jquery-ui/jquery-ui.min.js' %}"></script>
<script type="text/javascript" src="{% static 'bootstrap/dist/js/bootstrap.js' %}"></script>
<script src="{% static 'js/jquery.bootstrap.modal.forms.js' %}"></script>
<!-- You can alternatively load the minified version -->
<script src="{% static 'js/jquery.bootstrap.modal.forms.min.js' %}"></script>


<script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>

<script>
  AOS.init();
</script>
<!--
    _..-...
   ,Y+  .:.:\_
  | |./'     ``-\
  |,'`           `.
  |               `_
  |     ,-''-. ,-''':
  |    /      .'     :                                     ****lian was here****
  | .\ |    o  |__o.,'                           _.-' '\
 '|\| \\      /    `)                        ,..,'     ,'
  |`|  ' `..- .....<:                      ,'    `. ,-:
  ' ,-   _.-'        `.                 _,'       +'  |		^^^ BZZT BZZT ^^^
   |`|  ,'            '.              ,'       - _/_,'-\
    `.Y|   _,,.. ____./'           ,-'         /'|`'  _|
      ||  | |  |  | |           _.-              `--+'
      |-.  "|:.|..|-.    _,.. ,/'               ,..Y'
      / `\.       ,-'  ,' /,,'               _,'
     .:_    -----'''|.:   |             _,Y''
    /  '`'';'.     /:  \  |        _,Y-'
    |      |  ' .  | `._| |     _,'
_/-'';.. _ |     ` |   \   `.Y'i'                                           * MadTechnologies Copyright 2018-2019
,'    ,'    '             |    i/'                                          * MadWorks
,.'      /                   ..--'
|       |                     \
: .     /                      ' .
/'  `._ .'                         `.
/     _''                            \
/     ./                               \
/      /                                 \
/      |                                   \
/     ,'|                                   |


    -->

</body>


</html>